name: 'Setup k8s'
description: 'Setup kubectl, configure AWS credentials, login to ECR and update kubeconfig'
inputs:
  kubectl-version:
    description: 'kubectl version to be installed'
    default: 'v1.24.0'
  aws-access-key-id:
    description: 'AWS Access Key ID'
    required: true
  aws-secret-access-key:
    description: 'AWS Secret Access Key'
    required: true
  aws-region:
    description: 'AWS Region'
    required: true
    default: 'ap-southeast-1'
  eks-cluster-name:
    description: 'EKS Cluster Name'
    default: 'awds-dev'
outputs:
  dockerRegistry:
    description: 'Docker registry thru AWS ECR'
    value: ${{ steps.login-ecr.outputs.registry }}
runs:
  using: 'composite'
  steps:
    - name: Install kubectl
      uses:  azure/setup-kubectl@v3
      with:
        version: ${{ inputs.kubectl-version }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        # aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        # aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ inputs.aws-region }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Update kubeconfig and get namespaces
      shell: bash
      run: |
        aws eks update-kubeconfig --region ${{ inputs.aws-region }} --name ${{ inputs.eks-cluster-name }}
        kubectl get namespace
